version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"
  commands:
    # 1. Update pip and install Zensical along with python extensions
    - python -m pip install --upgrade pip
    - pip install zensical mkdocstrings-python

    # 2. Build your documentation static files using Zensical
    - zensical build

    # 3. Create the directory RTD requires and copy files over
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r site/* $READTHEDOCS_OUTPUT/html/
