version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"

jobs:
  install:
    - pip install zensical
  build:
    html:
      # Compiles your site into static HTML
      - zensical build
  post_build:
    # Moves the output to the directory Read the Docs expects
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
